export default {
    //action get pokemon kanto
    GET_POKEMON_KANTO:"GET_POKEMON_KANTO",
    GET_POKEMON_KANTO_FULFILLED:"GET_POKEMON_KANTO_FULFILLED",
    GET_POKEMON_KANTO_REJECTED:"GET_POKEMON_KANTO_REJECTED",
    GET_POKEMON_KANTO_PENDING:"GET_POKEMON_KANTO_PENDING",
    // action get Pokemon portada
    GET_POKEMON_PORTADA:"GET_POKEMON_PORTADA",
    GET_POKEMON_PORTADA_FULFILLED:"GET_POKEMON_PORTADA_FULFILLED",
    GET_POKEMON_PORTADA_REJECTED:"GET_POKEMON_PORTADA_REJECTED",
    GET_POKEMON_PORTADA_PENDING:"GET_POKEMON_PORTADA_PENDING",
    // action get Pokemon johto
    GET_POKEMON_JOHTO:"GET_POKEMON_JOHTO",
    GET_POKEMON_JOHTO_FULFILLED:"GET_POKEMON_JOHTO_FULFILLED",
    GET_POKEMON_JOHTO_REJECTED:"GET_POKEMON_JOHTO_REJECTED",
    GET_POKEMON_JOHTO_PENDING:"GET_POKEMON_JOHTO_PENDING",
    //ACTION GET POKEMON HOENN
    GET_POKEMON_HOENN:"GET_POKEMON_HOENN",
    GET_POKEMON_HOENN_FULFILLED:"GET_POKEMON_HOENN_FULFILLED",
    GET_POKEMON_HOENN_REJECTED:"GET_POKEMON_HOENN_REJECTED",
    GET_POKEMON_HOENN_PENDING:"GET_POKEMON_HOENN_PENDING",
    //ACTION GET POKEMON SINNOH
    GET_POKEMON_SINNOH:"GET_POKEMON_SINNOH",
    GET_POKEMON_SINNOH_FULFILLED:"GET_POKEMON_SINNOH_FULFILLED",
    GET_POKEMON_SINNOH_REJECTED:"GET_POKEMON_SINNOH_REJECTED",
    GET_POKEMON_SINNOH_PENDING:"GET_POKEMON_SINNOH_PENDING",
    //ACTION GET POKEMON UNOVA
    GET_POKEMON_UNOVA:"GET_POKEMON_UNOVA",
    GET_POKEMON_UNOVA_FULFILLED:"GET_POKEMON_UNOVA_FULFILLED",
    GET_POKEMON_UNOVA_REJECTED:"GET_POKEMON_UNOVA_REJECTED",
    GET_POKEMON_UNOVA_PENDING:"GET_POKEMON_UNOVA_PENDING",
    //ACTION GET POKEMON DETAILS
    GET_POKEMON_DETAILS:"GET_POKEMON_DETAILS",
    GET_POKEMON_DETAILS_FULFILLED:"GET_POKEMON_DETAILS_FULFILLED",
    GET_POKEMON_DETAILS_REJECTED:"GET_POKEMON_DETAILS_REJECTED",
    GET_POKEMON_DETAILS_PENDING:"GET_POKEMON_DETAILS_PENDING",
}